version: 2
groups:
  code-review:
    approve_by_comment:
      approve_regex: Approved|:shipit:|:\+1:|LGTM|shipit
      enabled: true
      reject_regex: ^Rejected
    required: 1
    reset_on_push:
      enabled: false
    users:
    - festinalente91
    - gogetteryoungun