language: node_js
node_js:
- node
notifications:
  slack:
    secure: Xl733a4QIRRBNTFo4wSDfNh5BO6szOOn+b7DIsfJt1APe32mpB0TfRooclJl9lt8sYAw7dkY2JdOT+QaZn2rwRnlssVShck8/hyCm9j0ZP9SC4u08C7CEbXbXanMi1U0foSC8T+BJklXPpMLM0fKOh8pcPTbF47k68UKHEfaGmm4uu4+jEc61hysWDsqtgt7AqP4rMxy57SxcyceWJ/JOX8hGDSlwTPASWzdmmhOlvQHfVa4YpG7hdd06f+CxGznR5Wgaba+4l7lyXE15vL/+rWyEmks6yAdcP08Mfp0rfRoOMFmHxq5j/BZhTYUzbQ69H8zpsnDTVYCglWVE//uG4OabitS5/bukNw0TiRru0V9kMzE+voTWMqPpSzMnOjz36MxlUNcx1kjIq72+AcJiz/RChZLvrtXRPUivufdNIOTM9rd3nBokvnJEhaI1qBHNjNSSTm3Gq7nSSlY0jIYegGSnxgGe3z+REKH7E2dhgMYuxMUXfT0yda3C0Ojf7VPQRjLrMhwWK3VwoojgVesn0mNHxHBuTbui2fuwp6RZxlTtlooJjywCUvQMnaznXnBAXXnF01QFz9cpWWNkB7qKDzk0ay8DGkrPum+1a49DcWoji7QBzSFsJxcHOG8L0rBl9ItXkXYUS+qG7Zwb4WCotVvE3ow2f0TF9Y5ZhzNF48=
